package com.example.sqli.config;

import com.example.sqli.util.DBFactory;
import org.springframework.boot.CommandLineRunner;
import org.springframework.stereotype.Component;

import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.ResultSet;
import java.sql.Statement;

@Component
public class DbInitializer implements CommandLineRunner {

    private final DBFactory dbFactory;

    public DbInitializer(DBFactory dbFactory) {
        this.dbFactory = dbFactory;
    }

    @Override
    public void run(String... args) throws Exception {
        initializeDatabase();
    }

    /**
     * Initialize the database by creating the users table if it doesn't exist.
     * This method is idempotent and can be called multiple times safely.
     * It's also public so it can be called when switching databases at runtime.
     */
    public void initializeDatabase() throws Exception {
        String dbType = dbFactory.getDbType().toLowerCase();

        try (Connection conn = dbFactory.getConnection()) {
            // Check if table exists using DatabaseMetaData (works for all databases)
            DatabaseMetaData meta = conn.getMetaData();
            ResultSet rs = meta.getTables(null, null, "users", new String[] { "TABLE" });

            if (rs.next()) {
                System.out.println(dbType + " Database: users table already exists.");
                return;
            }
            rs.close();

            // Table doesn't exist, create it
            String sql = getCreateTableSQL(dbType);

            if (!sql.isEmpty()) {
                try (Statement stmt = conn.createStatement()) {
                    stmt.execute(sql);
                    System.out.println("Initialized " + dbType + " Database: users table created.");
                }
            }
        } catch (Exception e) {
            System.err.println("Database initialization failed for " + dbType + ": " + e.getMessage());
            // We don't crash, maybe existing data is there or connection issue
        }
    }

    /**
     * Get the appropriate CREATE TABLE SQL for each database type
     */
    private String getCreateTableSQL(String dbType) {
        switch (dbType) {
            case "sqlite":
                return "CREATE TABLE users (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT, email TEXT)";

            case "mysql":
                return "CREATE TABLE users (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(255), email VARCHAR(255))";

            case "postgresql":
                return "CREATE TABLE users (id SERIAL PRIMARY KEY, name VARCHAR(255), email VARCHAR(255))";

            case "mssql":
                // Simple CREATE TABLE without IF NOT EXISTS to avoid Multiple ResultSets error
                return "CREATE TABLE users (id INT IDENTITY(1,1) PRIMARY KEY, name VARCHAR(255), email VARCHAR(255))";

            case "oracle":
                // Oracle 12c+ with identity column
                return "CREATE TABLE users (id NUMBER GENERATED BY DEFAULT AS IDENTITY, name VARCHAR2(255), email VARCHAR2(255), CONSTRAINT pk_users PRIMARY KEY (id))";

            default:
                return "";
        }
    }
}
